version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: stake-backend
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - app-net

  backend-canary:
    build:
      context: ./canary  # <-- Path to your canary backend build
    container_name: stake-backend-canary
    restart: always
    env_file:
      - .env
    ports:
      - "4001:4000"       # Internally also runs on port 4000
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - backend-canary
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
